create table if not exists public.model_registry (
    id bigint generated by default as identity primary key,
    model_name text not null,
    model_version text not null,
    training_dataset text not null,
    rmse double precision not null,
    r2 double precision not null,
    created_at timestamptz not null default now(),
    model_path text not null
);

create table if not exists public.dataset_materials (
    id bigint generated by default as identity primary key,
    material_name text not null,
    density double precision,
    melting_point double precision,
    thermal_conductivity double precision,
    specific_heat double precision,
    decomposition_temp double precision,
    glass_transition_temp double precision,
    created_at timestamptz not null default now()
);

create table if not exists public.analysis_runs (
    id bigint generated by default as identity primary key,
    analysis_id text unique,
    material_name text not null,
    material_class text,
    density double precision,
    melting_point double precision,
    thermal_conductivity double precision,
    additional_properties jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.analysis_results (
    id bigint generated by default as identity primary key,
    analysis_run_id bigint not null references public.analysis_runs(id) on delete cascade,
    dfrs double precision,
    confidence jsonb,
    feature_importance jsonb not null default '{}'::jsonb,
    prediction_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.custom_materials (
    id bigint generated by default as identity primary key,
    analysis_id text unique,
    material_name text not null,
    density double precision,
    melting_point double precision,
    thermal_conductivity double precision,
    descriptor_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.prediction_logs (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null default now(),
    material_name text,
    input_features jsonb not null default '{}'::jsonb,
    predicted_score double precision,
    confidence jsonb,
    model_version text
);

create table if not exists public.simulation_logs (
    id bigint generated by default as identity primary key,
    analysis_id text,
    material_name text not null,
    base_material jsonb not null default '{}'::jsonb,
    modifications jsonb not null default '{}'::jsonb,
    simulation_output jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
