"""Model-loading exports for the application runtime."""

from __future__ import annotations

from src.model import (
    ACTIVE_MODEL_CONFIG,
    COATINGS_LOOKUP_PATH,
    DATASET_BUILD_DATE,
    DATASET_VERSION,
    MATERIALS_LOOKUP_PATH,
    MODEL_ARTIFACT_PATH,
    MODEL_METADATA_PATH,
    MODEL_VERSION,
    PHASE3_REFERENCE_PATH,
    SUPPORTED_DATASET_VERSIONS,
    SUPPORTED_MODEL_VERSIONS,
    compute_confidence,
    compute_feature_interpretability,
    compute_training_variance_stats,
    get_coating_names,
    get_material_descriptors,
    get_material_names,
    get_model_artifact_path,
    get_model_metadata_path,
    initialize_dataset_metadata,
    inspect_model_schema,
    load_coating_lookup,
    load_material_lookup,
    load_phase3_model,
)

__all__ = [
    "ACTIVE_MODEL_CONFIG",
    "COATINGS_LOOKUP_PATH",
    "DATASET_BUILD_DATE",
    "DATASET_VERSION",
    "MATERIALS_LOOKUP_PATH",
    "MODEL_ARTIFACT_PATH",
    "MODEL_METADATA_PATH",
    "MODEL_VERSION",
    "PHASE3_REFERENCE_PATH",
    "SUPPORTED_DATASET_VERSIONS",
    "SUPPORTED_MODEL_VERSIONS",
    "compute_confidence",
    "compute_feature_interpretability",
    "compute_training_variance_stats",
    "get_coating_names",
    "get_material_descriptors",
    "get_material_names",
    "get_model_artifact_path",
    "get_model_metadata_path",
    "initialize_dataset_metadata",
    "inspect_model_schema",
    "load_coating_lookup",
    "load_material_lookup",
    "load_phase3_model",
]
